### ISSUE TITLE
感谢分享,觉得比mint ui 好 

### ISSUE THREAD

**Issue by lzd358194530** [Spikef/vmc#2]
缺少 mint ui 中的 cell swipe 功能组件
input 选中的样式  评分star 样式有点``` 难看

**Comment by Spikef** [comment]
可以考虑添加组件
样式的话因为没有设计稿，所以比较难看，可以尝试使用[less变量覆盖](https://github.com/Spikef/vmc#引入组件样式)的方式来调整样式

**Comment by lzd358194530** [comment]
import VMC from 'vmc/install'引入报错 
Module not found: Error: Can't resolve 'vmc/install' 找不到
import VMC from 'vmc/src/install' 还是有报错

**Comment by Spikef** [comment]
@lzd358194530 
从源码引用的话，应该是
```javascript
import VMC from 'vmc/src/install';
```
示例中的引用是因为配了`alias`指向了`src`目录；
报错的话可能是因为你没有配babel，或者将node_modules目录exclude掉了。
因为这个项目一直开源之后没有人使用，所以这些细节也就一直没有动力去优化。

**Comment by lzd358194530** [comment]
vue2 现在才开始慢慢用的多点  
我用vue-cli工具  照着文档 跑不起来 怎么都报错 用import VMC from 'vmc/src/install' 也不行
